CREATE TABLE IF NOT EXISTS catalog_sales (
    cs_sold_date_sk int,
    cs_sold_time_sk int,
    cs_ship_date_sk int,
    cs_bill_customer_sk int,
    cs_bill_cdemo_sk int,
    cs_bill_hdemo_sk int,
    cs_bill_addr_sk int,
    cs_ship_customer_sk int,
    cs_ship_cdemo_sk int,
    cs_ship_hdemo_sk int,
    cs_ship_addr_sk int,
    cs_call_center_sk int,
    cs_catalog_page_sk int,
    cs_ship_mode_sk int,
    cs_warehouse_sk int,
    cs_item_sk int,
    cs_promo_sk int,
    cs_order_number bigint,
    cs_quantity int,
    cs_wholesale_cost double precision,
    cs_list_price double precision,
    cs_sales_price double precision,
    cs_ext_discount_amt double precision,
    cs_ext_sales_price double precision,
    cs_ext_wholesale_cost double precision,
    cs_ext_list_price double precision,
    cs_ext_tax double precision,
    cs_coupon_amt double precision,
    cs_ext_ship_cost double precision,
    cs_net_paid double precision,
    cs_net_paid_inc_tax double precision,
    cs_net_paid_inc_ship double precision,
    cs_net_paid_inc_ship_tax double precision,
    cs_net_profit double precision,
    PRIMARY KEY (cs_item_sk, cs_order_number)
);
