CREATE TABLE IF NOT EXISTS catalog_returns (
    cr_returned_date_sk int,
    cr_returned_time_sk int,
    cr_item_sk int,
    cr_refunded_customer_sk int,
    cr_refunded_cdemo_sk int,
    cr_refunded_hdemo_sk int,
    cr_refunded_addr_sk int,
    cr_returning_customer_sk int,
    cr_returning_cdemo_sk int,
    cr_returning_hdemo_sk int,
    cr_returning_addr_sk int,
    cr_call_center_sk int,
    cr_catalog_page_sk int,
    cr_ship_mode_sk int,
    cr_warehouse_sk int,
    cr_reason_sk int,
    cr_order_number bigint,
    cr_return_quantity int,
    cr_return_amount double precision,
    cr_return_tax double precision,
    cr_return_amt_inc_tax double precision,
    cr_fee double precision,
    cr_return_ship_cost double precision,
    cr_refunded_cash double precision,
    cr_reversed_charge double precision,
    cr_store_credit double precision,
    cr_net_loss double precision,
    PRIMARY KEY (cr_item_sk, cr_order_number)
);
