CREATE TABLE IF NOT EXISTS item (
    i_item_sk int,
    i_item_id text,
    i_rec_start_date date,
    i_rec_end_date date,
    i_item_desc text,
    i_current_price double precision,
    i_wholesale_cost double precision,
    i_brand_id int,
    i_brand text,
    i_class_id int,
    i_class text,
    i_category_id int,
    i_category text,
    i_manufact_id int,
    i_manufact text,
    i_size text,
    i_formulation text,
    i_color text,
    i_units text,
    i_container text,
    i_manager_id int,
    i_product_name text,
    PRIMARY KEY (i_item_sk)
);
