CREATE TABLE IF NOT EXISTS store_sales (
    ss_sold_date_sk int,
    ss_sold_time_sk int,
    ss_item_sk int,
    ss_customer_sk int,
    ss_cdemo_sk int,
    ss_hdemo_sk int,
    ss_addr_sk int,
    ss_store_sk int,
    ss_promo_sk int,
    ss_ticket_number bigint,
    ss_quantity int,
    ss_wholesale_cost double precision,
    ss_list_price double precision,
    ss_sales_price double precision,
    ss_ext_discount_amt double precision,
    ss_ext_sales_price double precision,
    ss_ext_wholesale_cost double precision,
    ss_ext_list_price double precision,
    ss_ext_tax double precision,
    ss_coupon_amt double precision,
    ss_net_paid double precision,
    ss_net_paid_inc_tax double precision,
    ss_net_profit double precision,
    PRIMARY KEY (ss_ticket_number, ss_item_sk)
);
