CREATE TABLE IF NOT EXISTS store_returns (
    sr_returned_date_sk int,
    sr_return_time_sk int,
    sr_item_sk int,
    sr_customer_sk int,
    sr_cdemo_sk int,
    sr_hdemo_sk int,
    sr_addr_sk int,
    sr_store_sk int,
    sr_reason_sk int,
    sr_ticket_number bigint,
    sr_return_quantity int,
    sr_return_amt double precision,
    sr_return_tax double precision,
    sr_return_amt_inc_tax double precision,
    sr_fee double precision,
    sr_return_ship_cost double precision,
    sr_refunded_cash double precision,
    sr_reversed_charge double precision,
    sr_store_credit double precision,
    sr_net_loss double precision,
    PRIMARY KEY (sr_ticket_number, sr_item_sk)
);
