CREATE TABLE IF NOT EXISTS web_site (
    web_site_sk int,
    web_site_id text,
    web_rec_start_date date,
    web_rec_end_date date,
    web_name text,
    web_open_date_sk int,
    web_close_date_sk int,
    web_class text,
    web_manager text,
    web_mkt_id int,
    web_mkt_class text,
    web_mkt_desc text,
    web_market_manager text,
    web_company_id int,
    web_company_name text,
    web_street_number text,
    web_street_name text,
    web_street_type text,
    web_suite_number text,
    web_city text,
    web_county text,
    web_state text,
    web_zip text,
    web_country text,
    web_gmt_offset double precision,
    web_tax_percentage double precision,
    PRIMARY KEY (web_site_sk)
);
